### ISSUE TITLE
Indexing fails on second Elasticsearch.Store load?

### ISSUE THREAD

**Issue by aphillipo** [infinitered/elasticsearch-elixir#10] opened 2018-03-19 00:05 UTC
So I have implemented the Store, Document Protocol and a mapping file and I'm nearly getting things working with your great library.

Unfortunately it seems to be calling the Elasticsearch.Store load function twice even though there are fewer than 5000 entries for the first index.  I would have thought that it would never try to index again returned values < bulk_insert_size is the number of entries returned?

Returned from Elasticsearch.Store:

```elixir
[
    %MyApp.MyThing{....etc...},
    %MyApp.MyThing{....etc...},
    %MyApp.MyThing{....etc...}
]
```

It then gives me argument error when my Repo returns an empty array:

```
SELECT .... FROM tasks AS i0 LIMIT $1 OFFSET $2 [5000, 5000]
** (ArgumentError) argument error
    :erlang.apply([], :load, [])
    (elasticsearch) lib/elasticsearch/storage/data_stream.ex:57: Elasticsearch.DataStream.load_page/4
    (elixir) lib/stream.ex:1361: Stream.do_resource/5
    (elixir) lib/stream.ex:1536: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1911: Enum.reduce/3
    (elasticsearch) lib/elasticsearch/indexing/bulk.ex:81: Elasticsearch.Index.Bulk.upload/4
    (elasticsearch) lib/elasticsearch/indexing/index.ex:33: Elasticsearch.Index.hot_swap/4
    (elasticsearch) lib/mix/elasticsearch.build.ex:57: Mix.Tasks.Elasticsearch.Build.build/3
    (elasticsearch) lib/mix/elasticsearch.build.ex:39: anonymous fn/3 in Mix.Tasks.Elasticsearch.Build.run/1
    (elixir) lib/enum.ex:1911: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/enum.ex:3251: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1911: Enum.reduce/3
    (elasticsearch) lib/mix/elasticsearch.build.ex:37: Mix.Tasks.Elasticsearch.Build.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

I am using your library inside an umbrella project so that might be something to do with it?  I am a bit confused where to go from here! Ta!

**Comment by danielberkompas** [comment] 2018-03-19 20:17
@aphillipo thanks for the excellent bug report! I am investigating this now and will try and have a fix up by the end of the day.

**Comment by danielberkompas** [comment] 2018-03-19 20:27
@aphillipo as a followup, it would be helpful to see more details on your `Elasticsearch.Store` implementation. I'm having trouble reproducing the described behavior.

**Comment by aphillipo** [comment] 2018-03-19 20:43
Sure!

**Comment by aphillipo** [comment] 2018-03-19 20:46
```elixir
defmodule Fixes.IssueStore do
  @behaviour Elasticsearch.Store
  import Ecto.Query, only: [from: 2]

  @impl Elasticsearch.Store
  def load(Fixes.Issue, offset, limit) do
    query = from(i in Fixes.Issue, limit: ^limit, offset: ^offset, preload: [:creator])
    Fixes.Repo.all(query)
  end
end
```

And my issue_impl.ex is:

```elixir
defimpl Elasticsearch.Document, for: Fixes.Issue do
  def id(issue), do: issue.id
  def type(_issue), do: "issue"
  def parent(_issue), do: false

  def encode(issue) do
    %{
      issue_id: issue.issue_id,
      title: issue.title,
      description: issue.description,
      states: issue.states,
      creator: get_user_map(issue.creator)
    }
  end

  def get_user_map(user) do
    %{
      username: user.username,
      email: user.email,
      display_name: user.display_name,
      deleted_at: user.deleted_at
    }
  end
end
```

**Comment by aphillipo** [comment] 2018-03-19 20:49
I think I might have spotted it! Load should be a parameter not a Fixes.Issue 🤦🏻‍♂️

Sorry to have wasted your time!

**Comment by aphillipo** [comment] 2018-03-19 20:52
```elixir
defmodule Fixes.IssueStore do
  @behaviour Elasticsearch.Store
  import Ecto.Query, only: [from: 2]

  @impl Elasticsearch.Store
  def load(queryable, offset, limit) do
    query = from(i in queryable, limit: ^limit, offset: ^offset, preload: [:creator])
    Fixes.Repo.all(query)
  end
end
```

Still doesn't work sadly :-(

**Comment by danielberkompas** [comment] 2018-03-19 21:12
@aphillipo I haven't been able to reproduce this error yet. It appears to be that somehow, somewhere, the `store` module is being set to an empty list, causing an error when Elixir tries to call `store.load`:

```
:erlang.apply([], :load, [])
```

I haven't been able to find anything that would do that yet. I have to move on for now, but maybe can you try out my branch and see if it helps you?

```
{:elasticsearch, github: "infinitered/elasticsearch", branch: "10-argument-error"}
```

**Comment by aphillipo** [comment] 2018-03-19 21:20
Yes thanks for looking.  Seems very strange, I'll take a look!

**Comment by steffkes** [comment] 2018-04-16 07:16
i'm not entirely sure that i'm hitting the same problem .. but at least the error message looks exactly what @aphillipo posted in the beginning.

i'm in `load_page/4` and also seeing that `store` is a empty list - which made me curious what the other parameter values would be. `offset` and `limit` do look okay, but `source` ...

first run, everything okay:

```
source: MyApp.Event
store: MyApp.ElasticsearchStore
offset: 0
limit: 5000
```
while on the second run, it breaks due to:

```
source: %Elasticsearch.Exception{
  col: nil,
  line: nil,
  message: "Rejecting mapping update to [events-1523862388] as the final mapping would have more than 1 type: [post, event]",
  query: nil,
  raw: %{
    "_id" => "V+4Jvn21KnFHpE80KOs+glpUWznkv1gI7ZOjKhzRvrM=",
    "_index" => "events-1523862388",
    "_type" => "event",
    "error" => %{
      "reason" => "Rejecting mapping update to [events-1523862388] as the final mapping would have more than 1 type: [post, event]",
      "type" => "illegal_argument_exception"
    },
    "status" => 400
  },
  status: 400,
  type: "illegal_argument_exception"
}
store: []
offset: 0
limit: 5000
```
Because of #14 i'm thinking that this project is mainly based on 5.x - because for version 6.x onward there is an article about [Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html) which explains that

> Indices created in Elasticsearch 6.0.0 or later may only contain a single mapping type. Indices created in 5.x with multiple mapping types will continue to function as before in Elasticsearch 6.x. Mapping types will be completely removed in Elasticsearch 7.0.0.

i don't see (yet) why there would ever be two types in one index in my situation, because i've defined two indexes .. each one does have a (separated) type, but according to the error message .. i'd say they get merged somehow.

HTH

**Comment by aphillipo** [comment] 2018-04-16 09:06
{
  "mappings": {
    "_doc": {
      "properties": {
        "issue_id": {
          "type": "text",
          "fields": {
            "exact_issue_id": { "type": "keyword" }
          }
        },
        "title": { "type": "text" },
        "description": { "type": "text" },
        "type": { "type": "keyword" },
        "creator": {
          "properties": {
            "username": {
              "type": "text"
            },
            "display_name": {
              "type": "text"
            },
            "user_id": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

**Comment by steffkes** [comment] 2018-04-16 09:51
sorry, i should have been more precise .. but i'm guessing you're facing the same situation. you had 

```elixir
def type(_issue), do: "issue"
```

while your mapping shows `_doc`, that would be the same conflict i had. to get more debugging output, adding the following function to your `Store` module should output a similar message i got:

```elixir
def load(%Elasticsearch.Exception{} = exception, _, _, _) do
  IO.inspect(exception, label: "Elasticsearch.Exception")
end
```

(given all i know about my error right now). 

otherwise i'd suggest you debug your local dependency (adding some `IO.inspect`s in `Elasticsearch.DataStream.load_page/4` did the trick for me) and tell Elixir it should use the local one for `mix` by adding `path` to your dependency in `mix.exs`:

```elixir
{:elasticsearch, "~> 0.1.1", path: "deps/elasticsearch"}
```

**Comment by aphillipo** [comment] 2018-04-16 13:06
@steffkes that worked thanks so much!

**Comment by steffkes** [comment] 2018-04-16 14:07
@danielberkompas so what seems to be happening "on the second run" is basically just a failure while executing the first run - which just appears visible as part of the second one.

i'm not deep enough into this library yet to decide where to place additional error handling? because i'd say we need to drop out of the stream handling in this case and just bark. there is no way that we could fix this otherwise during runtime. 

my first idea was that we could maybe avoid the redundant definition of the type .. but i can't see how that would work. so we're only able to provide better error messages in case that it actually happens, or do i miss something?

**Comment by aphillipo** [comment] 2018-04-16 14:39
Better errors would be great if we've both bumped into this - that's why I haven't closed the issue yet.

**Comment by danielberkompas** [comment] 2018-04-16 16:11
So, if I'm understanding this right, this can happen whenever `DataStream` encounters an exception. I'll look into reproducing this via test.

Regarding the differences between Elasticsearch 5 and 6, are you saying that Elasticsearch no longer supports having multiple document types in the same index?

**Comment by steffkes** [comment] 2018-04-17 10:33
> Regarding the differences between Elasticsearch 5 and 6, are you saying that Elasticsearch no longer supports having multiple document types in the same index?

This is how [Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html) sounds to me, yes. They are describing the drawbacks of this approach as well as a few alternatives for new versions and the future.

> So, if I'm understanding this right, this can happen whenever DataStream encounters an exception. I'll look into reproducing this via test.

Yes, exactly this. based on the idea to place the handling inside `Store.load/4` I've refactored it - but i'm not sure it's the best place to have it, as well as the best way to handle it?

```patch
diff --git a/lib/elasticsearch/storage/data_stream.ex b/lib/elasticsearch/storage/data_stream.ex
index 1ad24fa..3ce9a3a 100644
--- a/lib/elasticsearch/storage/data_stream.ex
+++ b/lib/elasticsearch/storage/data_stream.ex
@@ -39,6 +39,10 @@ defmodule Elasticsearch.DataStream do
     {[], 0, Config.all()[:bulk_page_size]}
   end

+  defp next(_, %Elasticsearch.Exception{} = exception, _) do
+    raise exception
+  end
+
   # If no items, load another page of items
   defp next({[], offset, limit}, source, store) do
     load_page(source, store, offset, limit)
```

at least, this stops the stream cleanly and provides a stack trace. probably not the most valuable one .. but better than nothing i'd say

**Comment by danielberkompas** [comment] 2018-04-18 17:03
I'm going to patch the issue with `DataLoader` to raise any Elasticsearch exception it encounters like @steffkes suggests. Then, I'll cut the `0.2.0` release, and then focus on upgrading the library for Elasticsearch 6+. Some things will need to change now that we don't be having multiple types per index.

**Comment by danielberkompas** [comment] 2018-04-18 17:25
I'm confused again. I can't find any way that the `store` in `DataStream` would raise an exception, or that this exception would somehow get converted into the `store` position in the args.

It must be happening somewhere else in the execution chain, especially since `DataStream` has nothing to do with creating Elasticsearch indexes. It simply loads data from your data store.

Could either of you provide an example application? Or more detailed reproduction steps?

**Comment by steffkes** [comment] 2018-04-19 08:49
i don't think it's the store raising this one - to me it seems the origin is the HTTP-API, at least that would make sense, given that the same behaviour can be seen when you're using `curl` to send records towards elasticsearch's bulk endpoint.

the patch is just an idea/suggestion how to make the error visible - as i've said before i'm not sure if it's the best place or even a correct place at all. this was the first part of the chain where i could spot/handle it. 

i'll see that i put an example together where it's obvious and probably even find out where a better place to hook in would be.

**Comment by aphillipo** [comment] 2018-04-19 09:35
Can we not just check the config and the mapping have the same key for the mapping? That's what solved my issue.

**Comment by steffkes** [comment] 2018-04-19 10:33
Well yes, that would already help :) do you have an idea how/where to check this? because given the current structure, a type can be part of multiple indexes and during runtime we don't have an idea which index we're writing to (if i'm not mistaken) .. at least no somewhere where i'd probably integrate such an assertion

**Comment by steffkes** [comment] 2018-04-19 10:34
and .. on the other hand, the way it's suggested .. it would solve probably all error cases, no matter what. from "not able to connect to this host" to something like "dude, you've made some configuration mistake" - everything would be caught this way

**Comment by steffkes** [comment] 2018-04-19 13:36
> Could either of you provide an example application? Or more detailed reproduction steps?

kept it as simple as possible @danielberkompas .. configuration (which btw yielded another issue which i'll file afterwards), (static) store, entity & mapping: https://github.com/steffkes/elasticsearch-elixir-10

where the relevant things to note are the different identifiers between [elasticsearch's posts mapping](https://github.com/steffkes/elasticsearch-elixir-10/blob/b3c07da96b03799f8d2488a1295183bffd00d6c0/priv/elasticsearch/posts.json#L3) and [the post entity](https://github.com/steffkes/elasticsearch-elixir-10/blob/b3c07da96b03799f8d2488a1295183bffd00d6c0/lib/post.ex#L7) - one time we're using `post`, the other time `not-post`

**Comment by aphillipo** [comment] 2018-04-19 15:38
Thanks for doing this @steffkes!

**Closed** 2018-04-19 20:32 UTC

**Comment by steffkes** [comment] 2018-04-20 08:01
you're welcome @aphillipo, this was a nice trip :)
